### ISSUE TITLE
Native language names in language selection

### ISSUE THREAD

**Issue by Vegechu** [wlewisgames/caveblazers-translations#10]
When my language is set to German, the language selection still displays "German", instead of "Deutsch".
Solutions could be: 
- Keep it as it is and always display English names for all languages
- Display everything in the current language
- Display each name in their respective language, regardless of which language is currently selected

Also, I'd like to suggest to switch the language only after pressing the save settings button. Suppose you have all languages installed, it would save a lot of loading time when cycling through them.

**Comment by drchengyangwang** [comment]
Hi Vegechu,

You need to change the language name in `languages.ini`. I did so with Chinese translation and the in-game display was correct.
> [1]
name = "English"
file = "Languages/English_GB.json"
[2]
name = "简体中文"
file = "Languages/Chinese_S_ZH.json"

-CW

**Comment by Vegechu** [comment]
Oh, I see. Thanks for the information.
