### ISSUE TITLE
Certain Chinese characters will not be displayed

### ISSUE THREAD

**Issue by drchengyangwang** [wlewisgames/caveblazers-translations#12]
For example in line 39,
> "back": "返回",    

In game, “返”(fan) cannot be displayed while only “回”(hui) can. If I use another two-character word “回退” (hui-tui) as an alternative translation, both “回”(hui) and “退”(tui) can be displayed correctly, which proves that it's not about the limit of character length.

-CW

**Comment by drchengyangwang** [comment]
Both simplified and traditional Chinese translations have been 100% completed. Still, some characters cannot be displayed due to an unknown issue. @wlewisgames let me know if you need my help identifying the problem.

-CW

**Comment by wlewisgames** [comment]
I added 返 in the last update, so that should work now. Do you know how many other characters are missing?

**Comment by drchengyangwang** [comment]
@wlewisgames There are too many random missing characters, but I might have a solution.

I used [an online tool](http://www.zhtoolkit.com/apps/wordlist/create-list.cgi) in conjunction with [another one](https://www.qqxiuzi.cn/zh/quchong/), and created a spreadsheet that include all unique Chinese words and characters that occurred in the language file.

Please download the spreadsheet [here](https://www.dropbox.com/s/7pjrof29yhgxgvu/Caveblazer%20Unique%20Chinese%20Words.xlsx?dl=0). Note there are two sheets in the same file, one for all words and the other for all characters.

Hope this helps.

-CW

**Comment by drchengyangwang** [comment]
Updated the spreadsheet for unique Chinese words and characters.

- CW

**Comment by wlewisgames** [comment]
Thanks for the help! These characters should all be working now in v1.3.1c, but let me know if there's any that still don't work

**Comment by drchengyangwang** [comment]
All simplified Chinese characters are now correctly displayed. There is still some issue with traditional Chinese characters (e.g. 灑 臺). These characters were included in my spreadsheet so it's quite odd.

-CW
