### ISSUE TITLE
Some Japanese character not be displayed

### ISSUE THREAD

**Issue by igaguri132** [wlewisgames/caveblazers-translations#13]
Character of "奨","録" not be displayed in game.

**Comment by wlewisgames** [comment]
Thanks! I'll add those for the next version

**Comment by wlewisgames** [comment]
These characters should work now (as of v1.3.1b), are there any other characters missing?

**Comment by igaguri132** [comment]
Thanks to adding characters.
At present I want to add 称、茎、早、漏、感、罠、飾、連、蝙、験、応、銅、竜、道、程、団、暴、民、賢、酷、早、ヵ、両.

**Comment by igaguri132** [comment]
In addition I can't open "Toggle Enemies" in Japanese.
What should I do?
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Draw Event
for object objCustomModeOptionsPanel:

string_width argument 1 incorrect type (undefined) expecting a String (YYGS)
############################################################################################
--------------------------------------------------------------------------------------------
called from - gml_Object_objCustomModeOptionsPanel_Draw_64 (line 177)

**Comment by wlewisgames** [comment]
I'll make some changes to the japanese font settings for the next version. How much do you have translated? It would be good to commit your changes & submit a pull request to get your changes in the master repo - that way I can make sure all of the characters in your Japanese_JA.json file are supported in-game.

The error you're getting looks like one of the enemies in your translation does not have a tag - check through the enemy tags (e.g. m_slime, m_hobgoblin) from line 378 onwards to make sure they're all there.

**Comment by wlewisgames** [comment]
The japanese font should now work for all the characters in Japanese.JA.json
