### ISSUE TITLE
Discrepancy between Chinese_S_ZH.json and English_GB.json

### ISSUE THREAD

**Issue by drchengyangwang** [wlewisgames/caveblazers-translations#4]
Hi Will,

First off, thank you for creating my recent favorite rougelike game. I just discovered the DLC and bought it to verify my translation text.

There is some discrepancy between Chinese_S_ZH.json and English_GB.json. Note line 239 in the image below:

![language file discrepancy](https://user-images.githubusercontent.com/37681836/43006706-6279ceda-8c04-11e8-8a36-4f8136d8f068.PNG)

I have checked the Google [spreadsheet](https://docs.google.com/spreadsheets/d/1gwRiBYikRrkdn3Jlg9Q-LY_lg19Mxzfg4KG4jiX7eBg/edit#gid=0) and it looks like the English_GB.json file merely misses a few lines.

-CW

**Comment by wlewisgames** [comment]
Thanks! Looks like I added an older version of the English file to the repo - I've now updated it
