### ISSUE TITLE
Item description: Wide words freeze the game upon item selection

### ISSUE THREAD

**Issue by Vegechu** [wlewisgames/caveblazers-translations#6]
If a word is too wide to fit the item description panel, the game freezes when the respective item is selected from the inventory. Character length doesn't appear to matter.

WWWWWWWWWWW and
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii

are both okay, adding an additional character to either will cause a freeze.

**Comment by wlewisgames** [comment]
Fixed in v1.3.1a, thanks again! 👍
