### ISSUE TITLE
Missing entries

### ISSUE THREAD

**Issue by Vegechu** [wlewisgames/caveblazers-translations#9]
Daily traits "Bigger Explosions!" and "Extra Life!" as well as overhead messages "friendly!" and "+5 max health" (presumably from Blessing of Might) have no entry.

**Comment by wlewisgames** [comment]
Good spot, thanks! I've added "friendly" and "hostile" tags now. The blessing of might text will be updated for the next version & I haven't yet gotten around to adding the new daily traits.
